fpr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # admin page
    path('admin/', admin.site.urls),
    # '' = home page. fpr_db.urls = all the urls in the app
    path('',include('fpr_db.urls')),
    path('user/', include('users.urls')),
]

fpr_db/urls.py
# comments in power point to help understand this page

from django.urls import path
from . import views

app_name = 'fpr_db'

urlpatterns = [
    path('',views.index, name='index'),
    path('camps',views.camps, name='camps'),
    path('new_student/', views.new_student, name='new_student'),
    path('camp/<int:camp_id>/', views.camp, name='camp'),
    path('students',views.students, name='students'),
    path('parents',views.parents, name='parents'),
    path('camp_sign_up/<int:camp_id>/', views.camp_sign_up, name='camp_sign_up'),
]

users/urls.py
from django.urls import path, include
from . import views 

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

fpr_db/models.py
from django.db import models
from django.contrib.auth.models import User


#grade choices for the parent to select from on the new_student form
grade_choices = ['1','2','3','4','5','6','7','8','9','10','11','12']

# Create your models here

class Parent(models.Model):
    fname = models.CharField(max_length=50)
    # students
    lname = models.CharField(max_length=50)
    email = models.CharField(max_length=50, null=True)
    phone = models.CharField(max_length=14, null=True)
    address = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=30, null=True)
    state = models.CharField(max_length=15, null=True)
    zipcode = models.CharField(max_length=5, null=True)


class Employee(models.Model):
    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    phone = models.CharField(max_length=14)


class Camp(models.Model):
    name = models.CharField(max_length=40)
    #student = models.ForeignKey(Student, on_delete=models...)
    start_date = models.DateField(auto_now=False, auto_now_add=False, null=True)
    end_date = models.DateField(auto_now=False, auto_now_add=False, null=True)
    description = models.CharField(max_length=2000, null=True)
    cost = models.FloatField(default='0.00')
    
class Student(models.Model):
    #camp = models.ForeignKey(Camp, on_delete=models.CASCADE)
    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=50)
    phone = models.CharField(max_length=14)
    email = models.CharField(max_length=50,null=True)
    address = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=30, null=True)
    state = models.CharField(max_length=15, null=True)
    zipcode = models.CharField(max_length=5, null=True)
    bday = models.DateField(blank=True, null=True)
    grade = models.CharField(max_length=2, default='n/a')
    comment = models.CharField(max_length=150, default='n/a')
    owner = models.ForeignKey(User, on_delete=models.CASCADE,default=2)


class CampRegistration(models.Model):
    transaction_date = models.DateField(auto_now=True, auto_now_add=False)
    payment_received = models.CharField(max_length=1)   # Y or N
    student = models.ForeignKey(Student, on_delete=models.CASCADE,null=True)
    camp = models.ForeignKey(Camp, on_delete=models.CASCADE,null=True)
    notes = models.CharField(max_length=150, default='n/a')

users/models.py
from django.db import models

# Create your models here.

fpr_db/forms.py
from django import forms

from .models import Student, CampRegistration, Parent

class StudentResForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"
        #fields = ['fname', 'lname', 'phone', 'bday','grade','comment']
        



class CampSignUpForm(forms.ModelForm):
    class Meta:
        model = CampRegistration
        fields = ['student','payment_received']
        labels = {'student':"Enter your child's ID",'payment_received':'Would you like to pay now? (Y or N)'}

fpr_db/views.py
from django.shortcuts import render, redirect

from .forms import StudentResForm, CampSignUpForm

from .models import Camp, Student, Parent, CampRegistration

from django.contrib.auth.decorators import login_required

from django.http import Http404

#from .models import 


# Create your views here.

# request = user request of info from web page
def index(request):
    return render(request, 'fpr_db/index.html')

@login_required
def camps(request):
    camps = Camp.objects.order_by('end_date')

    context = {'camps':camps}

    return render(request, 'fpr_db/camps.html', context)

@login_required
def new_student(request):
    if request.method != 'POST':
        form = StudentResForm()
    else:
        form = StudentResForm(data=request.POST)
        if form.is_valid():
            new_student = form.save(commit=False)
            new_student.owner = request.user
            new_student.save()
            return redirect('fpr_db:students')

    context = {'form':form}

    return render(request, 'fpr_db/new_student.html', context)

@login_required
def camp(request, camp_id):
    camp = Camp.objects.get(id=camp_id)

    context = {'camp':camp}

    return render(request, 'fpr_db/camp.html', context)

@login_required
def students(request):
    students = Student.objects.filter(owner=request.user).order_by('lname')

    context = {'students':students}

    return render(request, 'fpr_db/students.html', context)

@login_required
def parents(request):
    parents = Parent.objects.order_by('lname')

    context = {'parents':parents}

    return render(request, 'fpr_db/parents.html', context)

@login_required
def camp_sign_up(request, camp_id):
    camp = Camp.objects.get(id=camp_id)
    if request.method != 'POST':

        form = CampSignUpForm()
    
    else:
        form = CampSignUpForm(data=request.POST)

        if form.is_valid():
            camp_sign_up = form.save(commit=False)
            camp_sign_up.camp = camp
            camp_sign_up.save()
            form.save()
            return redirect('fpr_db:camp', camp_id=camp_id)

    context = {'form':form, 'camp':camp}
    return redirect(request, 'fpr_db/camp_sign_up.html', context)

users/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import login

from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    '''Register a new user.'''
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('fpr_db:index')
            
    context = {'form': form}
    return render(request, 'registration/register.html', context)

fpr_db/templates/fpr_db/base.html
<p>
    <a href="{% url 'fpr_db:index' %}">Family Point Resources</a>
    <a href="{% url 'fpr_db:new_student' %}">New Student</a>
    <a href="{% url 'fpr_db:camps' %}">Camps</a>
    <a href="{% url 'fpr_db:parents' %}">Parents</a>
    <a href="{% url 'fpr_db:students' %}">Students</a>
    {% if user.is_authenticated %}
    Hello, {{user.username}}
    <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
    <a href="{% url 'users:register' %}">Register</a>
    <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>

{% block content %} {% endblock content %}

fpr_db/templates/fpr_db/camp.html
{% extends "fpr_db/base.html" %}

{% block content %}
<p>
    {{ camp.name }}
</p>
<p>
    <a href="{% url 'fpr_db:camp_sign_up' camp.id %}">Sign a child up for this camp</a>
</p>
<p>
    Duration: {{ camp.start_date }} to {{ camp.end_date }}
</p>
<p>
    {{ camp.description }}
</p>


{% endblock content %}

fpr_db/templates/fpr_db/camp_sign_up.html
{% extends "fpr_db/base.html" %}

{% block content %}
    <p>
        <a href= "{% url 'fpr_db:camp' camp.id %}">{{ camp.name }}</a>
    </p>

    <p>Sign a child up for this camp.</p>

    <form action= "{% url 'fpr_db:camp_sign_up' camp.id %}" method='post'>

        {% csrf_token %}


        {{ form.as_p }}

    <button name="submit">Add child</button>
    </form>
{% endblock content %}

fpr_db/templates/fpr_db/camps.html
{% extends "fpr_db/base.html" %}

{% block content %}

<p>Camps</p>

<ul>
    {% for camp in camps %}
    <li><a href="{% url 'fpr_db:camp' camp.id %}">{{ camp.name }}</a></li>
    {% empty %}
    <li>No camps have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}

fpr_db/templates/fpr_db/index.html
{% extends "fpr_db/base.html" %}

{% block content %}

<p>Family Point Resources</p>

<p>
    FamilyPoint Resources engages our community in supportive relationships that 
    build hope, meet needs, and transform lives.
</p>

{% endblock content %}

fpr_db/templates/fpr_db/new_student.html
{% extends "fpr_db/base.html" %}

{% block title %} Enroll a new student {% endblock title %}

{% block content %}
<form action="{% url 'fpr_db:new_student' %}"method ='post'>
    {% csrf_token %}

    {{ form.as_p}}

    <button name="Enroll">Add entry</button>

</form>

{% endblock content %}

fpr_db/templates/fpr_db/parents.html
{% extends "fpr_db/base.html" %}

{% block content %}

<p>Parents</p>

<ul>
    {% for parent in parents %}
    <li>{{ parent.id }} {{ parent.fname }} {{ parent.lname }} {{ parent.phone }} {{ parent.email }} {{ parent.address }} {{ parent.city }} {{ parent.state }} {{ parent.zip }}</li>
    {% empty %}
    <li>No parents have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}

fpr_db/templates/fpr_db/students.html
{% extends "fpr_db/base.html" %}

{% block content %}

<p>Students</p>

<ul>
    {% for student in students %}
    <li>{{ student.id }} {{ student.fname }} {{ student.lname }} {{ student.phone }} {{ student.email }} {{ student.address }} {{ student.city }} {{ student.state }} {{ student.zip }}</li>
    {% empty %}
    <li>No students have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}